// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFO7ERhOkqEFG4zQLmO3tmJqFnO5I9Bl4',
    appId: '1:852764709622:android:d2bff3ebc705eabd1412d7',
    messagingSenderId: '852764709622',
    projectId: 'flutter-e-commerce-aeb71',
    storageBucket: 'flutter-e-commerce-aeb71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ruw5xnH9toh2KcoVNnmE5aGCXJCrM5k',
    appId: '1:852764709622:ios:c78c004d95f7f2f91412d7',
    messagingSenderId: '852764709622',
    projectId: 'flutter-e-commerce-aeb71',
    storageBucket: 'flutter-e-commerce-aeb71.appspot.com',
    androidClientId: '852764709622-5uabvhna97edu5v349ae8ej7f4g86cup.apps.googleusercontent.com',
    iosClientId: '852764709622-nn0fl7hbevlqjmt474m3jvp104qclmh4.apps.googleusercontent.com',
    iosBundleId: 'com.oalshokri.chatAppClass',
  );
}
